### ISSUE TITLE
Portfolio: Deploy

### ISSUE THREAD

**Issue by waelelsafty07** [waelelsafty07/Portfolio#8]
This is live demo for portfolio [Link live](https://waelelsafty07.github.io/Portfolio/)

**Comment by LionRouge1** [comment]
Hi @waelelsafty07, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
